image:
  file: .gitpod.Dockerfile

tasks:
  - name: terminal1
    init: pip3 install pylint pycodestyle
    command: |
      printf 'export PATH="%s:$PATH"\n' "~/.local/bin" >> $HOME/.bashrc && exit
      source ~/.bashrc
      clear
vscode:
  extensions:
    - ms-python.python
    - njpwerner.autodocstring
